version: '3.7'
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=check_client_db
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=ivan
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5438:5432"
volumes:
  db: